// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7I2eBQpfkeopvwZwMvxa0xplTHrZNx_E',
    appId: '1:531127866597:android:4e7bd4fc28674f4ea2f00c',
    messagingSenderId: '531127866597',
    projectId: 'alkhal-fb819',
    storageBucket: 'alkhal-fb819.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnHFaPi43ZifQ-FHSFJ5x_g4vTFDR6Erc',
    appId: '1:531127866597:ios:c06a6c941e84dbaaa2f00c',
    messagingSenderId: '531127866597',
    projectId: 'alkhal-fb819',
    storageBucket: 'alkhal-fb819.firebasestorage.app',
    androidClientId: '531127866597-8ksrcr52a13eoonu8m39fg2t9q95covk.apps.googleusercontent.com',
    iosClientId: '531127866597-dh612sa55q287up31jj3se2gosl10npt.apps.googleusercontent.com',
    iosBundleId: 'com.khal.deliveryvendor',
  );
}
